version: "3.7"

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017-27019:27017-27019

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081 